backend/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  # Teste Views
  resources :item_carrinho, only:[:create, :update, :destroy]
  resources :carrinho, only:[:show]
  resources :favorito, only:[:index, :create, :destroy]
  
  # publico
  namespace :api do
    namespace :v1 do
      resources :albums, only: [:index, :show] do
        collection do
          get :search
        end
      end
      resources :artists, only: [:index, :show]
      resources :carrinho, only: [:show]
      resources :item_carrinho, only: [:create, :update, :destroy]
      resources :favorito, only: [:index, :create, :destroy]
    end
  end

  # admin
  namespace :admin do
    resources :albums
    resources :artist
  end


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

backend/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  belongs_to :genero
  has_many :item_carrinhos
  has_many :favoritos
  has_many :users, through: :favoritos, source: :user

  validates :spotify_id, presence: true, uniqueness:true
  validates :nome, presence: true
  validates :preco, presence: true
  validates :estoque, presence:true
  validates :artist, presence:true
  validates :genero, presence:true

end

backend/app/controllers/admin/albums_controller.rb
module Admin
  class AlbumsController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin!

    def index
      albums = Album.all
      render json: albums
    end

    def create
      album = Album.new(album_params)
      if album.save
        render json: album
      else
        render json: { errors: album.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def update
      album = Album.find(params[:id])
      if album.update(album_params)
        render json: album
      else
        render json: { errors: album.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def destroy
      album = Album.find(params[:id])
      album.destroy
      head :no_content
    end

    private

    def album_params
      params.require(:album).permit(:spotify_id ,:nome, :url_capa, :preco, :estoque, :data_lancamento, :artista_id, :genero_id)
    end

    def authorize_admin!
      render json: { error: "Acesso não autorizado" }, status: :unauthorized unless current_user.admin?
    end

  end
end

backend/app/controllers/api/v1/albums_controller.rb
module Api
  module V1
    class AlbumsController < ApplicationController
      before_action :authenticate_user!, except: [:index, :show, :search]

      def index
        albums = Album.all
        render json: albums.as_json(include: [:artist, :genero])
      end

      def show
        album = Album.find(params[:id])
        render json: album
      end

      def search
        query = params[:q]
        albums = Spotify::AlbumSearchService.new(query).call

        render json: albums.as_json(include: [:artist, :genero])
      end

    end
  end
end

backend/app/helpers/albums_helper.rb
module AlbumsHelper
end

backend/app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

backend/app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

backend/app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

backend/app/views/albums/index.html.erb
<h1>Albums#index</h1>
<% if user_signed_in? %>
    <h2><%=current_user.email%></h2>
<%end%>

<h2>Buscar albums:</h2>
<%= form_with url:search_albums_path, method: :get, local: true do |form| %>
    <%= form.text_field :q, placeholder: "Digite o nome do Album"%>
    <%= form.submit "Buscar" %>
<%end%>

<div>
    <% @albums.each do |album| %>
        <div>
            <h3><%= album.nome %> - <%= album.artist.nome %>: <%= link_to "Artista", artist_path(album.artist.id) %></h3>
            <p><img src="<%= album.url_capa %>" alt="<%= album.nome%>"></p><br>
            <p> <%= link_to "Detalhes", album_path(album.id) %> </p><br>
        </div>
    <%end%>
</div>

backend/app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

backend/app/views/albums/show.html.erb
<h1>Albums#show</h1>

<h1><%= @album.nome %></h1>

<div>
    <p>Artista: <%= @album.artist.nome %> | <%= link_to "Detalhes", artist_path(@album.artist.id) %></p><br>
    <p><img src="<%= @album.url_capa %>" alt="<%= @album.nome%>"></p><br>
    <p>Preco: <%= @album.preco %></p><br>
    <p>Estoque: <%= @album.estoque %></p><br>
    <p>Data Lancamento: <%= @album.data_lancamento %></p><br>
    <p>ID Spotify: <%= @album.spotify_id %></p><br>
    <p>Genero: <%= @album.genero.nome %> </p>
</div>

<%= button_to "Favoritar", favorito_index_path(album_id: @album.id), method: :post %>

<%= form_with url: item_carrinho_index_path, method: :post, local: true do |form|%>
    <%= form.hidden_field :album_id, value: @album.id %>
    <%= form.number_field :quantidade, min: 1, max: @album.estoque, value:1 %>
    <%= form.submit "Adicionar ao Carrinho" %>
<%end%>

<br>
<% if user_signed_in? %>
    <%= button_to 'Exit', destroy_user_session_path, method: :delete, local: true %>
<%end%>

<%= link_to "Voltar", albums_path %>

backend/app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>